project_name: amicontained

builds:
  - id: amicontained
    main: .
    binary: amicontained
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0          # no C dependencies => fully static with pure-Go stdlib
    tags:
      - netgo                  # pure-Go DNS resolver (avoid libc)
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -extldflags '-static'  # produce a static binary on Linux

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: raesene
    name: amicontained

